In [ ]:
import numpy as np

# The Basics

In [ ]:
a = np.array([1,2,3])
print(a)
b = np.array([[1.0,2.5,3.0],[4.6,5.7,6.9]])
print(b)

[1 2 3]
[[1.  2.5 3. ]
 [4.6 5.7 6.9]]


In [ ]:
#Getting Dimensions
a.ndim

1

In [ ]:
c = np.array(a, dtype = bool)
print(c)

[ True  True  True]


In [ ]:
adim = a.ndim
bdim = b.ndim
print(adim, bdim)

1 2


In [ ]:
#Getting Shape of Array
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

In [ ]:
#Data Types
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
#Memory Size
a.itemsize

8

In [ ]:
c = b.itemsize
print(c)

8


In [ ]:
a.nbytes

24

# Accessing/Changing Specific Elements, Rows, Columns

In [ ]:
a = np.array([[1,2,3,4,],[6,7,8,9],[10,11,12,13]])
print(a)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 13]]


In [ ]:
a.shape

(3, 4)

In [ ]:
#Getting specific elements [r, c]
a[1,1] #Starts from 0

7

In [ ]:
#Get a specific row
a[0, :] #for first row

array([1, 2, 3, 4])

In [ ]:
a[:,:]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a[:, 4] shows error

SyntaxError: ignored

In [ ]:
a[:,3]

array([ 4,  9, 13])

In [ ]:
a[1, 1:3]

array([7, 8])

In [ ]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a = a.reshape(4,3)
a[1,1] = 29
print(a)

[[ 1  2  3]
 [ 4 29  7]
 [ 8  9 10]
 [11 12 13]]


In [ ]:
a[:,2] = [100,1000,10000,100000]
print(a)

[[     1      2    100]
 [     4     29   1000]
 [     8      9  10000]
 [    11     12 100000]]


In [ ]:
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
c.ndim

3

In [ ]:
c[1, 1, 0] #getting specific element
#you can also replace similiarly

7

# Initializing Different Types of Array

In [ ]:
#All Zero Matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#All One Matrix
np.ones((4,2,3,4)) #You can use dtype as well

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [ ]:
#Any other number
np.full((2,2), 99, dtype = int)

array([[99, 99],
       [99, 99]])

In [ ]:
np.full(a.shape, 7) #Any other number (full_like) which is equal to (below)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.full_like(a, 4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(0,100).reshape(10,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [ ]:
# Random
np.random.rand(4,2) #You don't insert a tuple but just directly. Difficult to remember but important


array([[0.42514235, 0.29158665],
       [0.80136068, 0.57400162],
       [0.0205889 , 0.92079498],
       [0.90913838, 0.62272928]])

In [ ]:
np.random.randint(-4, 8, size = (3,3))

array([[ 7,  4,  4],
       [-2, -4, -3],
       [-4, -3,  5]])

In [ ]:
#Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
#Inserting array into array
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 7
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 7. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 7. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Important!!! We aren't copying the arrays here

a = np.array([1,2,3])
b = a
b[0] = 100

print(b)
print(a)

[100   2   3]
[100   2   3]


In [ ]:
#Solution- copy() function
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 7

array([ 8,  9, 10, 11])

In [ ]:
a - 7

array([-6, -5, -4, -3])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a ** 5

array([   1,   32,  243, 1024])

In [ ]:
b = np.array([100,101,102,103])
a + b

array([101, 103, 105, 107])

In [ ]:
a * b

array([100, 202, 306, 412])

In [ ]:
a / b

array([0.01      , 0.01980198, 0.02941176, 0.03883495])

In [ ]:
#Taking the sine, cosine, etc.
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


# Linear Algebra

In [ ]:
# Matrix Multiplication
a = np.ones((2,3))
print(a)
b = np.full((3,5), 7)
print (b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


array([[21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.]])

In [ ]:
#Calculation of determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [ ]:
# Check Documentation for More
# Multiplication
# Trace
# Singular Vector Decomposition
# Eigen Values
# Matrix Norm
# Inverse
# Etc.

# Statistics

In [ ]:
stats = np.array([[1,4,13],[3,5,10]])
stats

array([[ 1,  4, 13],
       [ 3,  5, 10]])

In [ ]:
np.min(stats, axis = 1)

array([1, 3])

In [ ]:
np.min(stats, axis = 0)

array([ 1,  4, 10])

In [ ]:
np.max(stats, axis = 0)

array([ 3,  5, 13])

In [ ]:
np.max(stats)

13

In [ ]:
np.sum(stats, axis = 0)

array([ 4,  9, 23])

In [ ]:
np.sum(stats)

36

# Reorganising Arrays

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b = a.reshape((1,8))
print(b)

[[1 2 3 4 5 6 7 8]]


In [ ]:
b = a.reshape((2,2,2))
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Stacking Arrays/Vectors
v1 = np.array([[1,2,3,4],[5,6,7,8]])
v2 = np.array([[3,45,56,76], [300,301,302,303]])
np.vstack([v1,v2,v1]) #Square Brackets or Round (any)

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  3,  45,  56,  76],
       [300, 301, 302, 303],
       [  1,   2,   3,   4],
       [  5,   6,   7,   8]])

In [ ]:
np.hstack([v1,v2])

array([[  1,   2,   3,   4,   3,  45,  56,  76],
       [  5,   6,   7,   8, 300, 301, 302, 303]])

Split is also there instead of stack

# Miscellaneous

In [ ]:
# Loading Data from Files (txt,csv to array)
# Advanced Indexing & Boolean Masking

In [ ]:
v1 > 5

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [ ]:
v1[v1 > 5]

array([6, 7, 8])